version: '3.9'

services:
  front-end-service:
    image: guillesaez15/golang_microservices_front_end:latest
    build:
      context: ./front-end
      dockerfile: front-end-service.dockerfile
    restart: always
    ports: 
      - "80:80"
    deploy: 
      mode: replicated
      replicas: 1
    networks:
      - golang-microservices

  broker-service:
    image: guillesaez15/golang_microservices_broker:latest
    build:
      context: ./broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports: 
      - "3000:80"
    deploy: 
      mode: replicated
      replicas: 1
    networks:
      - golang-microservices

networks:
  golang-microservices:
    driver: bridge