version: '3.9'

services:
  front-end-service:
    container_name: golang_microservices_front_end_service
    image: guillesaez15/golang_microservices_front_end
    restart: always
    ports: 
      - "80:80"
    deploy: 
      mode: replicated
      replicas: 1
    networks:
      - golang-microservices

  broker-service:
    container_name: golang_microservices_broker_service
    image: guillesaez15/golang_microservices_broker_service
    restart: always
    ports: 
      - "3000:80"
    deploy: 
      mode: replicated
      replicas: 1
    networks:
      - golang-microservices

networks:
  golang-microservices:
    driver: bridge